На проверку
java-park-mail-ru/fighting-02-2017 pull request #1
Opened 2017-02-23 14:41 UTC by dondiego4697

2017-02-28 10:26 UTC, KSolovyev requested changes

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/objects/ObjUser.java
> +        this.sessionkey = sessionkey;
login, nickname и email - не много ли?

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/sample/controllers/UserController.java
> +                answer.put("sessionkey", String.valueOf(httpSessionId));
зачем эта история с sessionkey, если есть куки?

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/sample/controllers/UserController.java
> +                answer.put("sessionkey", String.valueOf(httpSessionId));
Как вы будете хранить его, если я, например закрою вкладку? Или открою еще одну?

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/services/AccountService.java
> +            final Field[] currFields = currObjUser.getClass().getDeclaredFields();
Зачем? Делайте все через сеттеры

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/services/AccountService.java
> +    private Map<String, ObjUser> db;
давайте по-другому назовем. userNameToUser, например

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/services/AccountService.java
> +        if (login != null && db.get(login) != null) {
давайте уменьшим количество фигурных скобок и упростим:
```
if (login == null || db.get(login) == null) {
    callback.onError()
    return;
}
```

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/services/AccountService.java
> +        if (login != null && db.get(login) != null) {
с остальными кейсами нужно аналогично поступить

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/sample/controllers/UserController.java
> +    public String updateUser(@RequestBody ObjUser body, HttpSession httpSession) {
обратите внимание, что вам в ObjUser могут недосыпать полей или насыпать чего-то не того. Эти случаи стоит проверить

2017-02-28 10:26 UTC, KSolovyev commented on src/main/java/support/Encrypt.java
> +    private String encryptPassword(String password)
давайте будем хешировать пароль через spring.security. Мы чуть позже покажем как

2017-03-01 20:53 UTC, KSolovyev commented
отпишитесь, пожалуйста, как будет готово

2017-03-01 21:18 UTC, dondiego4697 commented
Здравствуйте. Я вроде залил последнее. Чего то не хватает?

2017-03-02 06:53 UTC, KSolovyev commented
Нет, просто оповещения о коммитах иногда не приходят, и мы не видим, что вы все поправили

2017-03-12 19:26 UTC, KSolovyev commented
Народ, сюда попали изменения с базой. Это следующий модуль и мы будем проверять их позже. Надо сделать повторный пул реквест из ветки, где будут только изменения первого модуля

2017-03-12 19:26 UTC, closed without merging