На проверку к рк 2
java-park-mail-ru/fighting-02-2017 pull request #3
Opened 2017-04-05 14:27 UTC by ChernovAndrey

2017-04-05 15:03 UTC, d-frolov commented
Почистите пожалуйста репозиторий от всякого мусора .idea  и т.п
и в git igonre добавьте. Тогда буду смотреть по существу.

Посмотрите как это сделано в других проектах

2017-04-05 16:12 UTC, ChernovAndrey commented
Почистил от мусора

2017-04-06 12:58 UTC, d-frolov requested changes

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/sample/controllers/UserController.java
> +    final static Logger log = Logger.getLogger(UserController.class.getName());
вот так пишите `Logger.getLogger(UserController.class);`

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/sample/controllers/UserController.java
>      private final String SESSIONKEY = "user";
static

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/sample/controllers/UserController.java
> +import org.springframework.transaction.PlatformTransactionManager;
паразитная зависимость

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/objects/HttpResponse.java
> +        System.out.print(newDomain);
Если уж подключили логгер, то выводить только через него

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/objects/ObjUser.java
>  public class ObjUser {
меня слово Obj в навании очень настораживает :)

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/sample/controllers/UserController.java
>          } catch (JSONException e) {
Это зачем?

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/sample/controllers/UserController.java
>          final JSONObject answer = new JSONObject();
А вы не хотите ответы обернуть в какой-нить красивый класс?

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/services/UserService.java
> +            if (rowNum == 0) throw new Exception();
ну так очень некрасиво :(

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/sample/controllers/UserController.java
> +    final static Logger log = Logger.getLogger(UserController.class.getName());
Общее замечание по коду - смотрите инспекции, они подсвечивают довольно много мелких ошибок

2017-04-06 12:58 UTC, d-frolov commented on src/main/java/services/UserService.java
> +        catch (Exception e){
По коду посмотрите инспекции, много чего существенного подсказывают

И на каждом файле сделайте автоформатирование кода

2017-04-06 16:02 UTC, ChernovAndrey commented
Вроде исправил)
Инспекции остались в основном только на sql диалект, не очень понял, про лидеров, что там лишнее?)

2017-04-09 21:39 UTC, KSolovyev commented
@d-frolov Дима, посмотри, тебя все устраивает?

2017-04-11 23:27 UTC, d-frolov requested changes

2017-04-11 23:27 UTC, d-frolov commented on src/main/java/sample/controllers/UserController.java
> +    private final static String SESSIONKEY = "user";
Скачайте пожалуйста профиль инспекций tp_java  и пригоните по коду. У вас горят детские ошибки, например надо  сменить порядок модификаторов

2017-04-13 14:05 UTC, KSolovyev commented on src/main/java/sample/controllers/UserController.java
> +    private final static String SESSIONKEY = "user";
подойдите ко мне на семинаре, я покажу

2017-04-13 14:24 UTC, ChernovAndrey commented
Вроде разобрался с инспекциями)

2017-04-20 15:11 UTC, merged