РК 3 без тестов и интеграции с фронтом
java-park-mail-ru/fighting-02-2017 pull request #4
Opened 2017-04-26 12:00 UTC by ChernovAndrey

2017-04-26 12:28 UTC, KSolovyev commented
а как вы тестировали? =)

2017-04-26 12:50 UTC, ChernovAndrey commented
Скачал приложение simple websocket client или как то так)
Все работает, могу скрин скинуть)

2017-04-26 12:59 UTC, KSolovyev commented
я хочу из вас программиста сделать, а не ручного тестировщика. Так что пишите тесты =)

2017-04-26 13:00 UTC, KSolovyev commented
А вообще, может успеете сделать текстовую версию фронта? Там не сложно должно быть, просто выводить результаты хода, без анимации

2017-04-26 13:36 UTC, ChernovAndrey commented
Ну к четвергу постараемся успеть)
Я просто решил залить без фронта, чтобы успеть до завтрашнего дня исправить недочеты по коду)

2017-04-28 05:25 UTC, ChernovAndrey commented
Ссылка на фронт https://stepfighting.herokuapp.com

2017-05-02 22:04 UTC, KSolovyev requested changes

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/Application.java
> +            data.setCoef();
Это должно происходить в сервисе ресурсной системы. Метод `setCoef()` - вообще жуть. Надо срочно избавиться от всех этих статических переменных

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/controllers/UserController.java
> +    /* @ExceptionHandler(Exception.class)
удалить, если не используется

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +    private static class Players {
давайте это отдельным классом сделаем, а не вложенным

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        private boolean snapFlag = false;
флаг избыточен. Можно проверять snap на null

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        private SnapClient moreEarlySnap;
почему поле так названо? Ведь другого snap'a у нас нет

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        final Coef coef1 = new Coef();
что это?

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        final Coef coef2 = new Coef();
что это?

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        if (snap1.hp < 0) snap1.hp = 0;
давайте использовать Math.max(..., 0)

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        if (snap1.hp.equals(0) || (snap2.hp.equals(0))) {
на всякий случай лучше всегда писать `snap1.hp <= 0`

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/support/Answer.java
>  public class Answer {
Сделайте из этого класса нормальную модель с полями, а не класс-хелпер

2017-05-02 22:04 UTC, KSolovyev commented on src/main/resources/application.properties
> +spring.datasource.password=8085772b6cde6b9fa22d83b90a4ffe2c947ea89da5a7e4bac5d95ecd6efbe637
пароль от базы на гитхабе?

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/SnapServer.java
> +    SnapServer(SnapClient snap1, SnapClient snap2, Integer takenDamage1, Integer takenDamage2) {
параметр должен быть `Map<SnapClient, Integer>` 
Дальше делаете damageMap.entrySet().stream().forEach(entry -> {
...
})
И избавляетесь от всего этого треша

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        } else {
return, else не нужен

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +            } else {
return, else не нужен

2017-05-02 22:04 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +                } else {
return, else не нужен

2017-05-02 22:04 UTC, KSolovyev commented
Правьте, потом еще посмотрю

2017-05-08 13:16 UTC, ChernovAndrey commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +                } else {
Но там же в конце еще для обоих игроков соединение закрывается, поэтому нельзя return делать отсюда, а если внести закрытие соединения в if, то получится 6 одинаковых строк

2017-05-08 13:18 UTC, ChernovAndrey commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        private SnapClient moreEarlySnap;
Чтобы подчеркнуть, что в сюда попадает тот снимок, который пришел раньше

2017-05-09 22:05 UTC, ChernovAndrey commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +                } else {
переписал метод)

2017-05-09 22:11 UTC, ChernovAndrey commented
Вроде поправил все ошибки, кроме интерфейса Mutual.

2017-05-09 22:13 UTC, ChernovAndrey commented on src/main/java/support/Answer.java
>  public class Answer {
Не понял, как это реализовать, у UsersData и Users всего одно общее поле и один общий метод, который реализован по-разному

2017-05-11 10:42 UTC, KSolovyev requested changes

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/sample/game/SnapServer.java
> +        map.forEach((snapClient, takenDamage) -> {
здесь нужна модель а не JSONObject

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/sample/game/SnapClient.java
> +    public @Nullable SnapClient(JSONObject json) {
тоже хочется через jackson

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/sample/websocket/Message.java
> +    public enum Type {step}
что за Type? почему это так выглядит?

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +        final SnapServer snapServer = new SnapServer(new HashMap<SnapClient, Integer>() {{
не надо использовать такую форму. Сделайте HashMap и просто добавьте туда значений

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/sample/game/Damage.java
> +    public Double MH;
что это?

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/sample/game/Damage.java
> +    public ArrayList<Integer> calculate(ArrayList<SnapClient> snap) {
`snaps`

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/sample/game/Damage.java
> +        for (int i = 0, j = 1; i < 2; i++, j--) {
Зачем здесь цикл?

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/sample/game/Damage.java
> +        for (int i = 0, j = 1; i < 2; i++, j--) {
без него вроде будет понятнее

2017-05-11 10:42 UTC, KSolovyev commented on src/main/java/support/Answer.java
> +    //public String getResult() {
надо убрать закомментированный код

2017-05-11 11:19 UTC, ChernovAndrey commented on src/main/java/sample/websocket/Message.java
> +    public enum Type {step}
В требованиях к третьему рк было сделать класс сообщений с возможностью расширения, подразумевается, что если сервер начнет поддерживать сообщения другого типа, то в enum добавится еще один тип сообщений

2017-05-11 11:20 UTC, ChernovAndrey commented on src/main/java/sample/game/Damage.java
> +        for (int i = 0, j = 1; i < 2; i++, j--) {
ну тут же две итерации

2017-05-11 11:52 UTC, KSolovyev commented on src/main/java/sample/websocket/Message.java
> +    public enum Type {step}
Ну так и назовите этт MessageType. И название enum-константы либо uppercase, либо с большой буквы. Каждую константу сделайте  с новой строки

2017-05-17 22:40 UTC, ChernovAndrey commented
Исправил замечания, но с модельками не совсем вышло разобраться. Например, если мне нужно преобразовать объект плюс еще какое-то поле  в JSON, возможно ли это как то сделать красиво через Jackson?
А что лучше использовать Jackson или Gson?

2017-05-18 10:09 UTC, KSolovyev commented
Не совсем понял про модельку, поясните. Вы хотите добавить в существующую модель еще одно произвольное поле? В этом случае делают либо nullable поле, либо другую модель

2017-05-18 10:10 UTC, KSolovyev commented
Gson стоит только в тестах использовать. И то выборочно

2017-05-18 10:16 UTC, KSolovyev requested changes

2017-05-18 10:16 UTC, KSolovyev commented on src/main/java/sample/game/Damage.java
> +        for (int i = 0, j = 1; i < 2; i++, j--) {
сделайте либо без цикла, либо без этих счетчиков. Нифига не понятно

2017-05-18 10:16 UTC, KSolovyev commented on src/main/java/sample/game/Damage.java
> +    public Double BB;
назовите понятно

2017-05-18 10:16 UTC, KSolovyev commented on src/main/java/sample/game/GameMechanicsSingleThread.java
> +    public void gmStemp(Players players) {
typo `Step`

2017-05-18 10:16 UTC, KSolovyev commented on src/main/java/sample/game/GameService.java
> +            } catch (IOException ignore) {
и все, ничего не делаем?

2017-05-18 10:16 UTC, KSolovyev commented on src/main/java/sample/websocket/Message.java
> +    public enum messageType {step}
с большой буквы, каждую константу с новой строки. Константы либо с большой буквы, либо заглавными

2017-05-18 14:03 UTC, ChernovAndrey commented
Поправил

2017-05-22 12:23 UTC, KSolovyev requested changes

2017-05-22 12:23 UTC, KSolovyev commented on src/main/java/sample/game/Damage.java
> +                blockOpponent = snaps.get(0).block;
вынесите это в функцию и зовите ее 2 раза

2017-05-23 13:16 UTC, ChernovAndrey commented
пока что не смотрите. Забыл, что открыт pull request

2017-05-24 08:31 UTC, KSolovyev commented
Напишите, когда смотреть тогда

2017-05-24 22:38 UTC, ChernovAndrey commented
Добавил многопоточность. Там есть закомментированный код, я пока что не могу его отладить, но то что не закомментировано, то работает

2017-05-25 17:26 UTC, ChernovAndrey commented
Откатился

2017-05-29 18:13 UTC, KSolovyev requested changes

2017-05-29 18:13 UTC, KSolovyev commented on src/main/java/sample/websocket/GameWebSocketHandler.java
> +            System.out.println(e.getMessage());
надо только логгером пользоваться

2017-05-29 18:13 UTC, KSolovyev commented on src/main/java/sample/websocket/GameWebSocketHandler.java
> +            log.error("Json error");
а в логгере прикреплять исключение

2017-05-29 18:13 UTC, KSolovyev commented on src/main/java/sample/game/SnapServer.java
> +    private JSONObject result;
так и не сделали модельки....

2017-05-29 18:27 UTC, ChernovAndrey commented on src/main/java/sample/game/SnapServer.java
> +    private JSONObject result;
JsonObject result не используется, забыл удалить, теперь просто Arraylist Snapclient преобразуется в json и отдается клиенту

2017-06-01 22:12 UTC, KSolovyev requested changes

2017-06-01 22:12 UTC, KSolovyev commented on src/main/java/sample/controllers/UserController.java
> +        public static final String login = "/login";
такие вещи принято UPPER_CASE писать

2017-06-01 22:14 UTC, KSolovyev commented
Выглядит норм, давайте мержить?

2017-06-02 11:44 UTC, ChernovAndrey commented
Давайте)

2017-06-02 13:32 UTC, KSolovyev commented
UPPER_CASE то поправьте

2017-06-02 14:46 UTC, ChernovAndrey commented
поправил и с модельками окончательно разобрался вроде

2017-06-02 16:40 UTC, KSolovyev commented
тревис отвалился =)

2017-06-02 18:09 UTC, ChernovAndrey commented
вроде сейчас все норм должно быть

2017-06-02 19:54 UTC, KSolovyev commented
🔥

2017-06-02 19:54 UTC, merged